apiVersion: apps/v1
kind: Deployment
metadata:
name: ml-api
spec:
replicas: 1
selector:
matchLabels:
app: ml-api
template:
metadata:
labels:
app: ml-api
spec:
containers:
- name: ml-api
image: gcr.io/YOUR_PROJECT_ID/fastapi-ml:v1
ports:
- containerPort: 8000